name: taknikat
description: A new Flutter application.
#ios 11/1
publish_to: 'none' 


version: 1.1.28+51

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^7.2.0
  provider: ^6.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.2.0
  pod_player: ^0.2.1
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_blurhash: ^0.8.2
  pretty_dio_logger: ^1.1.1
#  circular_menu: ^2.0.1
  star_menu: ^4.0.1

  flutter_timer_countdown: ^1.0.5
  multi_image_picker_view: ^1.0.3
  file_picker: ^8.0.0+1
  dotted_border: ^2.0.0+3
  modal_bottom_sheet: ^3.0.0-pre



  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^17.1.2
  firebase_auth:
  google_sign_in:
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  awesome_bottom_bar: ^1.2.2
  carousel_slider: ^4.2.1

  shimmer: ^3.0.0
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  # optimized_cached_image: ^3.0.1
  cached_network_image: ^3.3.0
  flutter_image_compress: ^2.1.0
  reactive_forms: ^17.0.1
  pin_code_fields: ^8.0.1
  intl_phone_number_input: ^0.7.0+2
  multi_select_flutter: ^4.1.2
  awesome_dialog: ^3.1.0
  flutter_svg:
  page_transition: ^2.0.5
  animations: ^2.0.8
  dots_indicator: ^3.0.0
  readmore: ^3.0.0
  chewie: ^1.5.0
  photo_view: ^0.15.0
  intl: ^0.18.0
  infinite_scroll_pagination: ^4.0.0
  flutter_staggered_animations: ^1.0.0
  device_preview: ^1.0.0
  firebase_core: ^2.13.1
  bot_toast: ^4.0.1
  flutter_app_badger: ^1.3.0
  timeago: ^3.2.2
  flutter_cart: ^0.0.7
  phone_numbers_parser: ^8.3.0
#  uni_links: ^0.5.1
  share_plus: ^7.2.2
  app_links: ^3.5.0

  flutter_flavor: any
  font_awesome_flutter: ^10.2.1
  html: ^0.15.1
  upgrader: ^10.3.0
  flutter_carousel_slider: ^1.1.0
  card_swiper: ^3.0.1

  # flutter_staggered_grid_view: ^0.6.2
  # pinput: ^2.2.7
  # select_dialog: ^2.0.0
  # dropdown_search: ^3.0.1
  # rxdart: ^0.27.3
  # built_value: ^8.3.0
  # dio_cookie_manager: ^2.0.0
  # rating_dialog: ^2.0.4
  # flutter_swiper: ^1.1.6
  # dotted_border: ^2.0.0+2
  # flutter_verification_code: ^1.1.3
  # flutter_bloc: ^8.1.1
  # flutter_rating_bar: ^4.0.0
  # smooth_star_rating: ^1.1.1
  # flutter_range_slider: ^1.5.0
  # video_player: ^2.4.2
  # form_builder_image_picker: ^4.0.0
  # local_file_screenshot_processor: ^0.0.2
  # cupertino_icons: ^1.0.4
  # flutter_html: any


dependency_overrides:
  sliver_tools: 0.2.12
  simple_animations: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  built_value_generator: ^8.3.0
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/
    - assets/images/flags/


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf


  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/taknikat.png"
  image_path_android: "assets/images/taknikat.png"
