// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6m_Y9HXK15BzAo4Ob_jKh3tQgpKpXxVM',
    appId: '1:777749023615:android:161cb62c7dfb07c9cb284a',
    messagingSenderId: '777749023615',
    projectId: 'taknikate',
    storageBucket: 'taknikate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAusOrE5N5WUFnGuFoL0KU0SudSuZPGuC4',
    appId: '1:777749023615:ios2:41ceb53844a93cffcb284a',
    messagingSenderId: '777749023615',
    projectId: 'taknikate',
    storageBucket: 'taknikate.firebasestorage.app',
    androidClientId: '777749023615-rr0jmb05ebad4e340n8s2qaij6qom407.apps.googleusercontent.com',
    iosClientId: '777749023615-7nngmna3d2q823532pis2t26cd1agkf9.apps.googleusercontent.com',
    iosBundleId: 'com.octopus.taknikat',
  );
}
